#!/bin/bash

# Include all of the functions that we need.
if [ -z ${FUNCTIONS_DIR+x} ]; then
  FUNCTIONS_DIR="${BASH_SOURCE%/*}/.."
  if [[ ! -d "$FUNCTIONS_DIR" ]]; then FUNCTIONS_DIR="$PWD/.."; fi
fi
. "$FUNCTIONS_DIR/pantheon-script-colours"
. "$FUNCTIONS_DIR/pantheon-cleanup-on-error"
. "$FUNCTIONS_DIR/pantheon-get-multidev-url"

##
# Check if the given plugin is installed.
#
# @param string $SITENAME
#   The machine name of the site.
# @param string $MULTIDEV
#   The machine name of the multidev.
# @param string $plugin_name
#
# @return boolean
#   1 if installed, else 0.
##
wp_check_if_plugin_installed() {
  local sitename=$1
  local multidev=$2
  local plugin=$3
  local url=''
  get_multidev_url $sitename $multidev url
  # @todo Abstract out into a function passed in by the caller.
  local sites=`terminus wp ${sitename}.${multidev} -- site list --url=$url --field=url`
  # @todo Need to iterate over all the WP Multisites.
  local active=`terminus wp ${sitename}.${multidev} plugin -- status $plugin | fgrep "Active"`
  if [ "$active" != "" ]; then
    return 1;
  fi
}

