#!/bin/bash

# Include all of the functions that we need.
if [ -z ${FUNCTIONS_DIR+x} ]; then
  FUNCTIONS_DIR="${BASH_SOURCE%/*}/.."
  if [[ ! -d "$FUNCTIONS_DIR" ]]; then FUNCTIONS_DIR="$PWD/.."; fi
fi
. "$FUNCTIONS_DIR/pantheon-script-colours"
. "$FUNCTIONS_DIR/pantheon-cleanup-on-error"

##
# Check if the given module is installed.
#
# @param string $SITENAME
#   The machine name of the site.
# @param string $MULTIDEV
#   The machine name of the multidev.
# @param string $module_name
#
# @return boolean
#   1 if installed, else 0.
##
drupal_check_if_module_installed() {
  local sitename=$1
  local multidev=$2
  local module=$3
  local has_features=1
  local installed=`terminus drush ${sitename}.${multidev} pm-list -- --status=enabled --pipe 2>/dev/null | fgrep $module`
  if [ "$installed" != "" ]; then
    return 1;
  fi
}

