#!/bin/bash

# Include all of the functions that we need.
FUNCTIONS_DIR="${BASH_SOURCE%/*}"
if [[ ! -d "$FUNCTIONS_DIR" ]]; then FUNCTIONS_DIR="$PWD"; fi
. "$FUNCTIONS_DIR/pantheon-script-colours"

##
# If there was an error, display it without cleaning anything up. Then exit.
#
# @param string $message
#   The message to display.
# @param int $return_code
#   What return code to send.
##
error_no_cleanup() {
  >&2 echo -e ""
  >&2 echo -e "${INVERSE}ERROR:"
  >&2 echo -e "$1${NOINVERSE}"
  >&2 echo -e ""
  exit "$2";
}