#!/bin/bash

# Include all of the functions that we need.
FUNCTIONS_DIR="${BASH_SOURCE%/*}"
if [[ ! -d "$FUNCTIONS_DIR" ]]; then FUNCTIONS_DIR="$PWD"; fi
. "$FUNCTIONS_DIR/pantheon-script-colours"
. "$FUNCTIONS_DIR/pantheon-error-no-cleanup"
. "$FUNCTIONS_DIR/pantheon-env-merge"

##
# Merge a multi-dev to dev.
#
# @param string $SITENAME
#   The machine name of the site.
# @param string $FRAMEWORK
#   The framework of the site.
# @param string $MULTIDEV
#   The machine name of the multidev.
##
multidev_merge() {
  local sitename=$1
  local framework=$2
  local multidev=$3

  # First merge master into dev.
  env_merge $sitename $framework 'dev' $multidev

  # Then merge the multidev into dev.
  env_merge $sitename $framework $multidev 'dev'
}
