#!/bin/bash

# Include all of the functions that we need.
FUNCTIONS_DIR="${BASH_SOURCE%/*}"
if [[ ! -d "$FUNCTIONS_DIR" ]]; then FUNCTIONS_DIR="$PWD"; fi
. "$FUNCTIONS_DIR/pantheon-script-colours"
. "$FUNCTIONS_DIR/pantheon-cleanup-on-error"

##
# Commit code.
#
# @param string $SITENAME
#   The machine name of the site.
# @param string $MULTIDEV
#   The machine name of the multidev (or 'dev' is acceptable too).
# @param string $DEFAULT_COMMIT_MESSAGE
#  The recommended commit message.
##
commit() {
  local sitename=$1
  local multidev=$2
  local default_commit_message=$3

  echo -e "feat: Committing code to $multidev on site $sitename"
  # Need to clear the cache before committing, otherwise it may not recognize
  # that files have changed.
  terminus -q env:clear-cache ${sitename}.${multidev}
  read -p "${UNDERLINE}Please provide git commit message [${BOLD}$default_commit_message${NOBOLD}]:${NOUNDERLINE} " commit_message
  commit_message="${commit_message:-$default_commit_message}"
  terminus -q env:commit ${sitename}.${multidev} --message="$commit_message" --force
  if [ $? != 0 ]; then
    cleanup_on_error $sitename $multidev "Error committing to git." 11
  fi
}
