#!/bin/bash
# pantheon-db-dump
# Dump a DB from a Pantheon environment.

if [[ $# -lt 2 ]] ; then
>&2  echo -e 'Usage:'
>&2  echo -e "  $(basename $0) [site] [environment] | drush sql-cli"
>&2  echo -e ' [site] - The name of a Pantheon site.  E.g. aclu-d7'
>&2  echo -e ' [environment] - An environment for that site.  E.g. dev'
>&2  echo -e ' The drush command may require `@something.local` or `-l foo.dev` or whatever you usually use to help it connect to the right database.'
  exit 0
fi

connection_info=`terminus connection:info $1.$2 --fields=mysql_port,git_port,sftp_username,mysql_host,mysql_username,mysql_password,mysql_database --format=print-r`

if [ $? -ne 0 ]; then
>&2  echo -e 'FAILURE. Please ensure that you can run this command successfully:'
>&2  echo -e ' terminus site connection-info'
  exit 1;
fi

mysql_port=`echo -e "$connection_info" | grep mysql_port | awk '{print $3}'`
git_port=`echo -e "$connection_info" | grep git_port | awk '{print $3}'`
if [ -z "$git_port" ]; then
  git_port=2222
fi
sftp_username=`echo -e "$connection_info" | grep sftp_username | awk '{print $3}'`
mysql_host=`echo -e "$connection_info" | grep mysql_host | awk '{print $3}'`
mysql_username=`echo -e "$connection_info" | grep mysql_username | awk '{print $3}'`
mysql_password=`echo -e "$connection_info" | grep mysql_password | awk '{print $3}'`
mysql_database=`echo -e "$connection_info" | grep mysql_database | awk '{print $3}'`

# First "Wake up" the server.
>&2 echo -e "--Now waking up the server.--"
terminus env:wake $1.$2

# Open the SSH connection.
>&2 echo -e "--Now opening the SSH connection.--"
#echo "ssh -o 'StrictHostKeyChecking accept-new' -f -N -L $mysql_port:localhost:$mysql_port -p $git_port $sftp_username@$mysql_host"
ssh -o 'StrictHostKeyChecking accept-new' -f -N -L $mysql_port:localhost:$mysql_port -p $git_port $sftp_username@$mysql_host

PV=''
if command -v pv >/dev/null 2>&1; then
  SIZE_BYTES=$(mysql --skip-column-names  --user=$mysql_username --host=127.0.0.1 --port=$mysql_port --password=$mysql_password $mysql_database <<< 'SELECT ROUND(SUM(data_length) * 0.8) AS "size_bytes" FROM information_schema.TABLES;')
  PV="pv --progress --timer --rate --size $SIZE_BYTES"
  >&2 echo -e "This progressbar is only an estimate.  If the transfer completes at less than 100% without errors, then it was successful."
fi

#Transfer the Database.
>&2 echo -e "--Now transfering the database.--"
mysqldump --no-autocommit --single-transaction -B --column-statistics=0 --opt --quote-names --user=$mysql_username --host=127.0.0.1 --port=$mysql_port --password=$mysql_password $mysql_database | $PV

# Kill the SSH session.
>&2 echo -e "--Now cleaning up the SSH connection.--"
ps -fU `whoami` | grep "ssh -f" | grep "@$mysql_host" | awk '{print $2}' | xargs kill

>&2 echo -e "All done"
