#!/bin/bash
# Bash script to run merge a Pantheon multidev into the dev environment.

# Include all of the subscripts that we need.
DIR="${BASH_SOURCE%/*}"
if [[ ! -d "$DIR" ]]; then DIR="$PWD"; fi
. "$DIR/functions/pantheon-script-colours"
. "$DIR/functions/pantheon-terminus-check"
. "$DIR/functions/pantheon-authenticate"
. "$DIR/functions/pantheon-choose-site"
. "$DIR/functions/pantheon-get-framework"
. "$DIR/functions/pantheon-multidev-merge"
. "$DIR/functions/pantheon-multidev-delete"
. "$DIR/functions/drupal/drupal-check-features"

#set -x

SUGGESTEDSITENAME=$1
if [ "$SUGGESTEDSITENAME" == "" ]; then
  terminus_check
  terminus_authenticate
fi
SITENAME=''
choose_site "$SUGGESTEDSITENAME" SITENAME
FRAMEWORK=''
get_framework "$SITENAME" FRAMEWORK

MULTIDEV=$2
if [ "$MULTIDEV" == "" ]; then
    terminus multidev:list $SITENAME
    echo -e "Choose a multidev to merge into dev."
    read -p "${UNDERLINE}Type the name of a multidev to merge into dev, and press [Enter] to continue:?${NOUNDERLINE} " MULTIDEV;
fi

case $FRAMEWORK in
  drupal)
    drupal_check_features "$SITENAME" "$MULTIDEV"
    hasfeatures=$?
    ;;
  *)
    echo -e "This script has no configuration management automation for $FRAMEWORK.  Unless this site has Quicksilver configured, you should probably just do everything manually."
    ;;

esac

multidev_merge "$SITENAME" "$FRAMEWORK" $MULTIDEV
multidev_delete "$SITENAME" "$MULTIDEV" 1

echo -e "Thanks.  All done."

