#!/bin/bash
# pantheon_quick_deploy.sh
# Deploy everything on dev straight to live.

if [ "$#" -lt 1 ]; then
  echo "Usage: pantheon_quick_deploy.sh [site name] [optional deployment message]"
  exit 1;
fi

if [ "$#" == 1 ]; then
  terminus env:deploy $1.test --cc && terminus env:deploy $1.live
else
  terminus env:deploy $1.test --cc --note "$2" && terminus env:deploy $1.live  --note "$2"
fi

