#!/bin/bash

# Include all of the functions that we need.
if [ -z ${FUNCTIONS_DIR+x} ]; then
  FUNCTIONS_DIR="${BASH_SOURCE%/*}/.."
  if [[ ! -d "$FUNCTIONS_DIR" ]]; then FUNCTIONS_DIR="$PWD/.."; fi
fi
. "$FUNCTIONS_DIR/pantheon-script-colours"
. "$FUNCTIONS_DIR/pantheon-cleanup-on-error"

##
# Import config from code to DB.
#
# It's assumed that drupal8_check_config_management has already been run.
#
# @param string $SITENAME
#   The machine name of the site.
# @param string $ENV
#   The machine name of the environment.
##
drupal_config_import() {
  local sitename=$1
  local env=$2
  local continue

  echo -e "Importing Configuration."
  terminus -q drush ${sitename}.${env} -- config-split-import -y
  if [ $? != 0 ]; then
    error_no_cleanup "Error running drush config-split-import." 15
  fi
  echo -e "Updating entities."
  terminus -q drush ${sitename}.${env_dest} -- entity-updates -y
  if [ $? != 0 ]; then
    error_no_cleanup "Error running drush entity-updates." 15
  fi
}
