#!/bin/bash

# Include all of the functions that we need.
if [ -z ${FUNCTIONS_DIR+x} ]; then
  FUNCTIONS_DIR="${BASH_SOURCE%/*}/.."
  if [[ ! -d "$FUNCTIONS_DIR" ]]; then FUNCTIONS_DIR="$PWD/.."; fi
fi
. "$FUNCTIONS_DIR/pantheon-script-colours"
. "$FUNCTIONS_DIR/pantheon-cleanup-on-error"
. "$FUNCTIONS_DIR/drupal8/drupal8-should-use-config-split"

##
# Show the overridden config.
#
# It's assumed that drupal8_check_config_management has already been run.
#
# @param string $SITENAME
#   The machine name of the site.
# @param string $ENV
#   The machine name of the environment.
# @param int $ISOVERRIDDEN
#   Is the config overridden?  TRUE== 1, FALSE == 0.  If indeterminate, then 1.
##
drupal_config_show_overridden() {
  local sitename=$1
  local env=$2
  local isoverridden=1
  local shoulduseconfigsplit=0

  drupal_should_use_config_split $sitename $env shoulduseconfigsplit

  if [ "$shoulduseconfigsplit" == 1 ]; then
    echo -e "Config differences can't be shown on the command line.  Instead, use the link below."
    local link=`terminus drush ${sitename}.${env} -- user-login 1 '/admin/config/development/configuration' 2>/dev/null`
    echo -e "  $link"
    return
  else
    echo -e "Checking for overridden config."
    local overridden=`terminus drush ${sitename}.${env} -- config-import -n --preview=list  2>/dev/null | fgrep -v "There are no changes to import" | fgrep -v 'Import the listed configuration changes?'`
    if [ "$overridden" != "" ]; then
      echo -e "$overridden"
      isoverridden=1
    else
      isoverridden=0
    fi
    eval "$3='$isoverridden'"
    return;
  fi
}
