#!/bin/bash

# Include all of the functions that we need.
if [ -z ${FUNCTIONS_DIR+x} ]; then
  FUNCTIONS_DIR="${BASH_SOURCE%/*}/.."
  if [[ ! -d "$FUNCTIONS_DIR" ]]; then FUNCTIONS_DIR="$PWD/.."; fi
fi
. "$FUNCTIONS_DIR/pantheon-script-colours"
. "$FUNCTIONS_DIR/pantheon-cleanup-on-error"
. "$FUNCTIONS_DIR/drupal/drupal-check-if-module-installed"

###
# Determine Drush version.
#
# @param string $SITENAME
#   The machine name of the site.
# @param string $MULTIDEV
#   The machine name of the multidev.
# @param $HASCONFIGMANAGEMENT
#   Will be overwritten with the either 1 (true) or 0 (false).
###
drupal8_check_config_management() {
  local sitename=$1
  local multidev=$2
  local hasconfigmanagement=1

  echo -e "Checking if Config module is installed."
  drupal_check_if_module_installed $sitename $multidev "config"
  if [ $? == 0 ]; then
    hasconfigmanagement=0
    eval "$3='$hasconfigmanagement'"
    return;
  fi
  eval "$3='$hasconfigmanagement'"
  echo -e "Checking that config is not overridden."
  # @todo Get skip-modules.
  local overridden=`terminus drush ${sitename}.${multidev} -- config-import -n --preview=list 2>/dev/null  | fgrep -v 'Import the listed configuration changes?'`
  if [ "$overridden" != "" ]; then
    echo -e "$overridden"
    cleanup_on_error $sitename $multidev "There are config overrides.  These should be cleaned up first. Probably just run \`drush config-import\`" 8
  fi
}

