#!/bin/bash

# Include all of the functions that we need.
if [ -z ${FUNCTIONS_DIR+x} ]; then
  FUNCTIONS_DIR="${BASH_SOURCE%/*}/.."
  if [[ ! -d "$FUNCTIONS_DIR" ]]; then FUNCTIONS_DIR="$PWD/.."; fi
fi
. "$FUNCTIONS_DIR/pantheon-script-colours"
. "$FUNCTIONS_DIR/pantheon-cleanup-on-error"
. "$FUNCTIONS_DIR/drupal8/drupal8-should-use-config-split"

##
# Import config from code to DB.
#
# It's assumed that drupal8_check_config_management has already been run.
#
# @param string $SITENAME
#   The machine name of the site.
# @param string $ENV
#   The machine name of the environment.
##
drupal_config_import() {
  local sitename=$1
  local env=$2
  local continue
  local shoulduseconfigsplit=0

  drupal_should_use_config_split $sitename $env
  shoulduseconfigsplit=$?

  echo -e "Importing Configuration."
  if [ "$shoulduseconfigsplit" == 1 ]; then
    terminus -q drush ${sitename}.${env} -- config-split-import -y
  else
    terminus -q drush ${sitename}.${env} -- config-import -y
  fi
  if [ $? != 0 ]; then
    error_no_cleanup "Error Importing configuration." 15
  fi
  echo -e "Updating entities."
  terminus -q drush ${sitename}.${env_dest} -- entity-updates -y
  if [ $? != 0 ]; then
    error_no_cleanup "Error running drush entity-updates." 15
  fi
}
