#!/bin/bash

# Include all of the functions that we need.
if [ -z ${FUNCTIONS_DIR+x} ]; then
  FUNCTIONS_DIR="${BASH_SOURCE%/*}/.."
  if [[ ! -d "$FUNCTIONS_DIR" ]]; then FUNCTIONS_DIR="$PWD/.."; fi
fi
. "$FUNCTIONS_DIR/pantheon-script-colours"
. "$FUNCTIONS_DIR/pantheon-cleanup-on-error"
. "$FUNCTIONS_DIR/drupal/drupal-check-if-module-installed"
. "$FUNCTIONS_DIR/drupal8/drupal8-config-show-overridden"
. "$FUNCTIONS_DIR/drupal8/drupal8-config-export"

###
# Check if Config is overridden.
#
# @param string $SITENAME
#   The machine name of the site.
# @param string $MULTIDEV
#   The machine name of the multidev.
#
# @return int
#   1 if config is overridden, else 0.
###
drupal8_check_config_management() {
  local sitename=$1
  local multidev=$2
  local hasconfigmanagement=1
  local isoverridden=0

  echo -e "Checking if Config module is installed."
  drupal_check_if_module_installed $sitename $multidev "config"
  if [ $? == 0 ]; then
    hasconfigmanagement=0
    return $hasconfigmanagement
  fi

  echo -e "Checking if Configuration Split module is installed."
  drupal_check_if_module_installed $sitename $multidev "config_split"
  if [ $? == 0 ]; then
    echo -e "${INVERSE}This site is not using Configuration Split module.  To avoid problem with accidentally enabling development modules/config on the live environment, see:${NOINVERSE}"
    echo -e "  https://www.advomatic.com/blog/using-configuration-split-to-have-dev-only-configuration-in-drupal-8"
    read -p "${UNDERLINE}Continue [${BOLD}y${NOBOLD}/n]${NOUNDERLINE} " continue;
    case $continue in
      [Nn]) error_no_cleanup "" 8 ;;
      *) ;;
    esac
  fi

  echo -e "Checking if config is overridden on ${multidev}."
  drupal_config_show_overridden $sitename $multidev
  isoverridden=$?
  if [ "$isoverridden" == 1 ]; then
    drupal_config_export $sitename $multidev 0
  fi
  return $hasconfigmanagement
}

