#!/bin/bash

# Include all of the functions that we need.
if [ -z ${FUNCTIONS_DIR+x} ]; then
  FUNCTIONS_DIR="${BASH_SOURCE%/*}/.."
  if [[ ! -d "$FUNCTIONS_DIR" ]]; then FUNCTIONS_DIR="$PWD/.."; fi
fi
. "$FUNCTIONS_DIR/pantheon-script-colours"
. "$FUNCTIONS_DIR/pantheon-cleanup-on-error"
. "$FUNCTIONS_DIR/pantheon-commit"
. "$FUNCTIONS_DIR/pantheon-get-multidev-url"
. "$FUNCTIONS_DIR/drupal/drupal-check-if-module-installed"
. "$FUNCTIONS_DIR/drupal/drupal-update"

###
# Update a Drupal site.
#
# @param string $SITENAME
#   The machine name of the site.
# @param string $MULTIDEV
#   The machine name of the multidev.
###
drupal8_update() {
  local sitename=$1
  local multidev=$2

  # @todo How do we mark modules as patched, and not needing updates?  Drush Locks?

  local installprofile=`echo 'print drupal_get_profile();' | terminus drush ${sitename}.${multidev} php-script 2>/dev/null -`
  echo -e "Install profile: $installprofile"
  if [ $installprofile == "" ]; then
    echo -e "${INVERSE}Warning${NOINVERSE} The install profile could not be determined.  Some install profiles cannot be updated with Drush.  Proceed with caution."
    echo -e ""
  fi
  # @todo also need a way to either check for composer managed packages, or to upgrade via composer.
  if [ $installprofile == "lightning" ]; then
    echo -e "${INVERSE}This site uses the Lightning distribution.${NOINVERSE}"
    echo -e "Drupal Core, and the contributed modules with Lightning "
    echo -e "cannot be upgraded using Drush.  Please upgrade a local copy of the"
    echo -e "site using the instructions at:"
    echo -e "  https://docs.google.com/document/d/1TI87rN2LpdB_2q3c4mx9CPWzYCQYDkxwBTztjMkDsR0"
    echo -e "You can still use this branch/multi-dev."
    echo -e ""
    return
  fi

  terminus -q drush ${sitename}.${multidev} -- pm-refresh -q
  local modulelist=''
  drupal_update_list_modules_needing_update $sitename $multidev modulelist

  echo -e ""
  echo -e "${BOLD}Remember that our security update policy does not include:${NOBOLD}"
  echo -e "* Jumps to a new major version."
  echo -e "  e.g. 8.x-2.4 to 8.x-3.0"
  echo -e "* Upgrading an alpha or dev module."
  echo -e "  e.g. 8.x-1.0-alpha3 to 8.x-1.0-beta2"
  echo -e "These should be done as billable work. And might involve back-porting patches rather than running upgrades."

  # @todo It would require less interaction if we did this a bit differently:
  #       1. Build a list of all the modules that we want to update.
  #       2. Update them one by one.  After each we ask for a commit message, as
  #          long as the user doesn't see any error messages.
  #       3. Ask the user to test the site.
  while true; do
    echo -e ""
    echo -e "${UNDERLINE}Enter one of the following:${NOUNDERLINE}"
    echo -e "* The machine-name of a module to update."
    echo -e "* 'list' to show the list again."
    echo -e "* 'none' to move on to the next step."
    read -p "? " module;
    case $module in
      none) break ;;
      list) drupal_update_list_modules_needing_update $sitename $multidev ;;
      *)
        if [ "$module" != "" ]; then
          drupal_update_module $sitename $multidev $module
          commit $sitename $multidev "Security update for $module module."
        fi
        ;;
    esac
  done;
}
