#!/bin/bash

# Include all of the functions that we need.
if [ -z ${FUNCTIONS_DIR+x} ]; then
  FUNCTIONS_DIR="${BASH_SOURCE%/*}/.."
  if [[ ! -d "$FUNCTIONS_DIR" ]]; then FUNCTIONS_DIR="$PWD/.."; fi
fi
. "$FUNCTIONS_DIR/pantheon-script-colours"
. "$FUNCTIONS_DIR/pantheon-cleanup-on-error"
. "$FUNCTIONS_DIR/pantheon-connection-mode"
. "$FUNCTIONS_DIR/pantheon-commit"
. "$FUNCTIONS_DIR/drupal8/drupal8-config-show-overridden"

##
# Check if config needs to be exported.
#
# @param string $SITENAME
#   The machine name of the site.
# @param string $MULTIDEV
#   The machine name of the multidev.
# @param int $CHECKFOROVERRIDES
#   Should the list of overrides be displayed?
#   In some scenarios they have already been shown.
##
drupal_config_export() {
  local sitename=$1
  local multidev=$2
  local checkforoverrides=$3
  local continue
  local isoverridden=0
  local shouldexport=0

  if [ "$checkforoverrides" == 1 ]; then
    echo -e "Clearing caches."
    terminus -q drush ${sitename}.${multidev} -- cache-clear all
    echo -e "Checking if config needs to be exported."
    drupal_config_show_overridden $sitename $multidev isoverridden
  fi

  if [ "$isoverridden" == 1 ] || [ "$checkforoverrides" == 0 ]; then
    echo -e "There are configuration overrides.  These should be probably be cleaned up first."
    if [ "$multidev" == "test" ]; then
      read -p "${UNDERLINE}Cannot export config on the test environment.
      [exit] so that you can clean up manually.
      [continue] on to the next step without making changes.${NOUNDERLINE} " continue;
    else
      read -p "
      ${UNDERLINE}[exit] so that you can clean up manually.
[auto] clean-up automatically (save all overrides to code, warning: only choose this if this environment has a fresh copy of the live database, or if these are your own changes that need to get back into code).
[continue] on to the next step without making changes.${NOUNDERLINE} " continue;
    fi
    # We can't assume that an auto cleanup should be default.  If we come across
    # overrides on dev it might be because the DB hasn't been refreshed in a
    # while.
    if [ "$continue" == "" ]; then
      continue="exit"
    fi
    if [ "$continue" == "exit" ]; then
      echo -e "You can clean up the config on this branch.  Then you can re-run this script to continue."
      exit 0
    elif [ "$continue" == "auto" ]; then
      connection_mode "$sitename" "$multidev" 'sftp'
      echo -e "Exporting config:"
      terminus drush ${sitename}.${multidev} -- config-export -y
      if [ $? != 0 ]; then
        cleanup_on_error $sitename $multidev "Error exporting configuration." 12
      fi
      commit $sitename $multidev "Regenerated configuration."
      connection_mode "$sitename" "$multidev" 'git'
    fi

  fi
}
