#!/bin/bash

# Include all of the functions that we need.
if [ -z ${FUNCTIONS_DIR+x} ]; then
  FUNCTIONS_DIR="${BASH_SOURCE%/*}/.."
  if [[ ! -d "$FUNCTIONS_DIR" ]]; then FUNCTIONS_DIR="$PWD/.."; fi
fi
. "$FUNCTIONS_DIR/pantheon-script-colours"
. "$FUNCTIONS_DIR/pantheon-cleanup-on-error"
. "$FUNCTIONS_DIR/drupal/drupal-get-drush-version"

##
# Does this site use an old version of Drush where we need to csim instead of cim?
#
# @param string $SITENAME
#   The machine name of the site.
# @param string $ENV
#   The machine name of the environment.
#
# @return int
#   1 if site uses old Drush, else 0.
##
drupal_should_use_config_split() {
  local sitename=$1
  local env=$2
  local framework='drupal8'
  local shoulduseconfigsplit=0

  local drushmajorversion=''
  local drushminorversion=''
  local drushpointversion=''
  drupal_get_drush_version "$sitename" $framework "$env" drushmajorversion drushminorversion drushpointversion

  # Drush cim only works to show overridden Config Split in Drush >= 8.1.10
  if [[ $drushmajorversion -eq 8 && $drushminorversion -lt 1 ]] || [[ $drushmajorversion -eq 8 && $drushminorversion -eq 1 && $drushpointversion -lt 10 ]]; then
    shoulduseconfigsplit=1
  fi
  return $shoulduseconfigsplit
}
